#include <iostream>
#include <iomanip>
#include <vector>
#include <array>
#include <string>
#include <memory>
#include <optional>
#include <map>
#include <unordered_map>
#include <queue>
#include <deque>
#include <set>
#include <algorithm>
#include <functional>
#include <cassert>
#include <sstream>
#include <fstream>